version: '3.8'

services:
  kvstore-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kvstore-server
    ports:
      - "50051:50051"
    environment:
      - PORT=50051
    command: [ "./server", "--port=50051" ]
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "50051" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - kvstore-network

  kvstore-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: kvstore-client
    depends_on:
      kvstore-server:
        condition: service_healthy
    environment:
      - SERVER_ADDR=kvstore-server:50051
    networks:
      - kvstore-network
    profiles:
      - client

networks:
  kvstore-network:
    driver: bridge
