version: '3.8'

services:
  kvstore-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: kvstore-server
    ports:
      - "50051:50051"
    environment:
      - PORT=50051
    command: [ "./kvstore-server", "--port=50051" ]
    networks:
      - kvstore-network

  kvstore-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: kvstore-client
    depends_on:
      - kvstore-server
    command: [ "./kvstore-client", "-addr=kvstore-server:50051" ]
    networks:
      - kvstore-network
    profiles:
      - client

networks:
  kvstore-network:
    driver: bridge
